### ISSUE TITLE
Update MySQL configuration doc

### ISSUE THREAD

**Issue by CollierCZ** [platformsh/platformsh-docs#1972]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/configuration/services/mysql.html

### What exactly should be updated?

Update for:
- Content accuracy
- Includes what it should
- Doesn't include what doesn't fit
- Fits template
- Fits style guide

### Additional context

Consider splitting out things like importing and exporting -- other tasks that might fit. Under the main service page in the hierarchy.

**Comment by CollierCZ** [comment]
Users have specifically complained about it being unclear how to define connections (like the `DATABASE_URL` for [Symphony Flex](https://github.com/platformsh/symfonyflex-bridge)). Make it clearer how to connect using `platform relationships` or the relationships variable.

**Comment by Pixelshaped** [comment]
Chiming in as @CollierCZ and I just had this conversation. I'll try to give more info without being too redundant.

Symfony user here. It was unclear to me at first how to connect to the DB, so I used the https://github.com/platformsh/symfonyflex-bridge bundle. But while it makes default credentials work magically (user:@database.internal) it's very brittle as it doesn't work for more advanced mysql/mariadb configurations.

After looking at the bundle code, I understood that the config was `DATABASE_URL=mysql://user:@database.internal:3306/main` and removed the bundle which was not very useful.

Then I modified my db relationships, adding a replication account as per documentation (https://docs.platform.sh/guides/general/mysql-replication.html), which made this not work again. Because the docs make the main user change from `user` to `mysql` which is unnecessary, but also because defining two endpoints creates passwords for those endpoints.

 It would just be better to explain the `platform relationships` command, which gives the proper `DATABASE_URL` (most notably returning auto-configured passwords which are created (in my understanding) when more than one endpoint exists for a db).
