### ISSUE TITLE
Document new `memory_limit` option behaviour

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#2917]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/languages/php.html#customize-php-settings

### What exactly should be updated?

Adding a custom `php.ini` used to overwrite CLI defaults. When users increased the `memory_limit` for PHP-FPM, they ended up lowering the limit for the CLI. 

Document behaviour post-bugfix => default values for CLI are enforced regardless of custom values in `php.ini`.
See Matthias's comment + context.

**Comment by matthiaz** [comment]
Correction.

```
Clarify that this behaviour can be avoided by moving the php_custom_config up for the CLI, so that the defaults come last and aren't overwritten. See context.```

This is not something the user can do. But this is going to be fixed in a soon to be release version of the php images.

The behaviour that will need to be documented is that we are currently overwriting the memory_limit = -1 and max_excution_time=0 settings. And will no longer do so after the bugfix gets released.

So basically, after the bugfix is released:
```
max_execution_time=0
max_input_time=-1
memory_limit=-1
``` will always be these values on php cli, regardless of what you put as custom values in php.ini

**Comment by AnouckColson** [comment]
Thank you @matthiaz for clarifying the need!

**Comment by AnouckColson** [comment]
Hi @matthiaz, could you please review [#2986](https://github.com/platformsh/platformsh-docs/pull/2986) and let me know if the information is correct and sufficient? Sorry for the delay, things have been busy since Aaron left.
