### ISSUE TITLE
Review Varnish snippet

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#2953]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/add-services/varnish.html#clear-cache-with-a-push

### What exactly should be updated?

We might need to update the snippet at step 2 of the procedure, or clarify which version it would work with (see feedback in context).

**Comment by chadwcarlson** [comment]
After some conversation, we found out the following:

- [Varnish 6.0 linked in the original discussion does in fact require](https://varnish-cache.org/docs/6.0/reference/vmod_generated.html#func-ip) a _fallback_ address, which would update the snippet to the below

```vcl

sub vcl_recv {
    if (req.method == "PURGE") {
        # The Platform.sh router provides the real client IP as X-Client-IP
        # Use std.ip to convert the string to an IP for comparison
        if (!std.ip(req.http.X-Client-IP, "0.0.0.0") ~ purge) {
            # Deny all purge requests not from the allowed IPs
            return(synth(403,"Not allowed."));
        }
        # Purge cache for allowed requests
        return (purge);
    }
    ...
}
```

- Since 7.0, however, this fallback is an optional field with a default value. 
- The ^same is the case previous to 6.x


Since this moves around quite a bit, I would suggest:

- Including a note, something like

> The snippet above has been produced for Varnish 7.x. If using a different version, consult the [Varnish documentation](https://varnish-cache.org/docs/) for potential differences in syntax and required parameters. 

@AnouckColson @gilzow Thoughts?
