### ISSUE TITLE
Rework SimpleSAML page

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#3011]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/guides/drupal9/simplesaml.html

### What exactly should be updated?

We got feedback that now that 2.0.x versions of SimpleSAML are available, our dedicated doc page is outdated (caters to 1.x versions). Let's rework and update it.

**Comment by gilzow** [comment]
Here's what I have uncovered so far (H/T to JB@MU)...

From the [simpleSAMLphp Authentication drupal module](https://www.drupal.org/project/simplesamlphp_auth): 

> Drupal core and SimpleSAMLphp compatibility
Drupal 9 is based on Symfony 4, Drupal 10 is based on Symfony 6. SimpleSAMLphp 1.x is compatible with Symfony 4, 2.x is compatible with Symfony 5. **Version 2.x is therefore not compatible with any Drupal core version and can not be used with this module**. Version 8.x-3.x of this module requires SimpleSAMLphp 1.x and can not be Drupal 10 compatible.

There is an [_alpha_ release of the module](https://www.drupal.org/project/simplesamlphp_auth/issues/3349278) that is compatible with D10, but:
> Drupal 10 has a dependency on Symfony 6. As of this release, **the underlying library, `simplesamlphp/simplesamlphp`, does not have a release that is compatible with Symfony 6.** The current version of its `master` branch is compatible with Symfony 6, but there is no roadmap for a release; it might be merged into the 2.x branch, _but it may not_.

At this point, I'm not sure we _can_ update the docs since it doesn't appear that there's an _official_ working combination beyond Drupal 9 and SimpleSAMLPhp v1.19.X
