### ISSUE TITLE
Document CPU limit for PHP-FPM sizing

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#3108]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/languages/php/fpm.html

### What exactly should be updated?

There's a hard limit on CPU which means that even with a lot of RAM, users may not be able to increase the number of workers. Make sure this is mentioned in the docs, see context.

**Comment by matthiaz** [comment]
Adding some context here

The amount of workers is calculated based on the memory. And that's usually only what customers needs to know.
It's at minimum: 2 workers
Calculation as documented already: `math.floor(old_div((memory - reserved_memory), request_memory)))`

However! On large containers with a lot of memory we are going to be adding so many workers that the cpu won't be able to handle it all. 

That's why there is a cpu limit as well but it will only kick in, if the memory calculation (listed above) ends up with 25 workers or more. The cpu limit is basically: amount of vCPU cores * 5. So if you have a 2XL container with 8 cpu cores, you will end up with at most 40 workers. Obviously, only if you have enough memory.

Feel free to ask me questions if anything is unclear
