### ISSUE TITLE
Some unparsed markdown on Node.js page

### ISSUE THREAD

**Issue by hannesvz** [platformsh/platformsh-docs#3136]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/languages/nodejs.html

### What exactly should be updated?

The project templates section has a list of collapsible boxes for all the various Javascript frameworks. Some of them have some unformatted markdown - backticks, [] links, etc.

Some examples:

* Under "Gatsby with Strapi" the text `gatsby-source-strapi` has the backticks visible and the text is unformatted.
* Same with the "Gatsby with WordPress" and "Node.js" sections
* The "Probot" section has a link that shows as `[Probot](https://github.com/probot/probot)` instead of a hyperlink

I think that's all of them but there may be more. These sections are pulled in from another source so I couldn't confirm the actual markdown in use here, but I suspect they are being escaped at the source.

**Comment by chadwcarlson** [comment]
Thanks @hannesvz! 

cc @gilzow This is another thing we can take a look at at enforcing standards/consistency, as this seems to be due to a mixture of Markdown/HTML in `.platform.template.yaml` files, when they should all be all HTML.

- [Gatsby Strapi ](https://github.com/platformsh/template-builder/blob/a19cbcfdfbaa68b6dda4e0c342e1b9597817faac/templates/gatsby-strapi/.platform.template.yaml#L7)
- [Gatsby WordPress](https://github.com/platformsh/template-builder/blob/a19cbcfdfbaa68b6dda4e0c342e1b9597817faac/templates/gatsby-wordpress/.platform.template.yaml#L7)
- [Probot](https://github.com/platformsh/template-builder/blob/a19cbcfdfbaa68b6dda4e0c342e1b9597817faac/templates/probot/.platform.template.yaml#L7)
