### ISSUE TITLE
Improve and Update Drupal Migration Docs

### ISSUE THREAD

**Issue by drclaw** [platformsh/platformsh-docs#355]
Hi,

I'm just going through the process of importing an existing Drupal site into platform and I think the [the docs](https://docs.platform.sh/drupal_migrate/guides/type/php/drupal/migrate/init.html) are a bit out of date:

**Page Order**

[Since July 2016](https://docs.platform.sh/user_guide/reference/upgrade/index.html#changes-in-version-2016-4) you can't actually push your code to platform without having the configuration files already created and committed to the repo. However, [this step in the tutorial](https://docs.platform.sh/drupal_migrate/guides/getting-started/import-code.html) comes _before_ [the configuration step](https://docs.platform.sh/drupal_migrate/guides/configuration/index.html) which is going to be confusing for users following step-by-step (like me).

Additionally the image in the "Import your codebase" step does not quite match what I'm seeing. This isn't that big a deal but it did lead me to consider that maybe the documentation was out of date.

**The "Public" or "Web" subdirectory**

Initially reading through the docs (the drupal tutorial and the main docs), I was confused by various references to a "public" directory. As it turns out I think platform used to automatically move the application files into a public subdirectory, but [that changed sometime earlier this year](https://docs.platform.sh/user_guide/reference/upgrade/index.html#changes-in-version-2016-3). 

However, it's still required that your code _be_ in a subdirectory which isn't actually mentioned in the "import your codebase" step. I think it should be mentioned earlier in the docs (maybe even as a prerequisite?) that your Drupal code cannot be at the root of the repository as many people's existing codebases may not be setup this way.

Thanks!

**Comment by Crell** [comment]
Hi @drclaw. I'm afraid when this issue was filed we were already in the process of eliminating the Drupal migration book, which rendered the page order changes obsolete.  Thank you for the PR, even if we weren't able to use it.

For the moment the migration guide has been replaced with https://docs.platform.sh/frameworks/drupal7/migrating.html. It doesn't cover as much, as the goal is to focus on data.  We're working on a better "getting started" section.

Meanwhile, if you spot any confusion about the "public" directory in the new docs can you file a PR for it?  We're not planning any more major overhauls in the foreseeable future, so they should be safe to file at this point.

Thanks for offering to help out!
