### ISSUE TITLE
Document how the # of URLs & their differences of your sites' URLs

### ISSUE THREAD

**Issue by skorasaurus** [platformsh/platformsh-docs#697]
I'd suggest to briefly explain how the number of URLs are generated when running `platform url -e idofyourenvironment` and the difference between these urls at https://docs.platform.sh/development/access-site.html#visiting-the-site-on-the-web

My guess that there are two URLs assigned for each route described in .platform/routes.yaml but I am not sure about this.

**Comment by Crell** [comment]
There's generally 2: an http and an https version of each.  (The HTTP one is usually just a redirect to HTTPS.)  Otherwise it should be 1:1 to what's in the routes.yaml file.

(We have a new "all" placeholder coming very soon that could result in more, depending on the domain configuration.)

How/where do you think that would make sense to explain?  Is it confusing currently?

**Comment by skorasaurus** [comment]
As a newer user (within the past month) to platform, the routes configuration page is a good place that explains routes.yaml's function and why routes.yaml exists. 

You just did a good job, stating the relationship between ```platform url ``` and routes.yaml that platform url -e environment_name will match that environment's routes.yaml with 2 urls (and HTTP and an HTTPs) per entry in routes.yaml 
explicitly mentioning that there are generally two routes just as you stated and that it would match what's in the routes.yaml. 

I'd suggest placing this at https://docs.platform.sh/development/access-site.html#visiting-the-site-on-the-web

**Comment by Crell** [comment]
Let's continue over in #729.  Thanks!
