### ISSUE TITLE
Information missing from installing solr on D8 doc

### ISSUE THREAD

**Issue by skorasaurus** [platformsh/platformsh-docs#717]
There's possibly some important pieces missing from the documentation for [using solr on d8 in platform](https://docs.platform.sh/frameworks/drupal8/solr.html#configuration)

I had followed the documentation and lastly, added the section at the bottom of the [page](https://docs.platform.sh/frameworks/drupal8/solr.html#configuration) to my [settings.platform.php](https://gist.github.com/skorasaurus/83715c6d475a4f42a5642d7cb87641f8)

After following that documentation and expecting a generic solr server to run, I had to make several other undocumented modifications for my solr server to work. 

A couple variables for the solr server need to be modified and they can be obtained by ssh'ing into your environment and issuing `echo $PLATFORM_RELATIONSHIPS | base64 --decode | json_pp`

- platform does not use the default port for the search_api (8983) but instead uses 8080. 
- the host value needs to be modified "solr.internal"

Perhaps related to[ this drupal bug ](https://www.drupal.org/project/drupal/issues/2744057)that is mentioned at the bottom of the platform doc page, I wasn't able to do have these modifications work by editing these values into my configuration YAMLs and committing them to platform; but only by modifying them directly at admin/config/search/search-api/server/default_solr_server/edit

**Comment by Crell** [comment]
Hm.  Interesting.  The code block you copied is supposed to obviate the need to modify the config object directly.  It is supposed to override the saved values, although it will *not* show differently in the UI.  The UI doesn't look at overridden values.  That's a tricky core bug, I believe.

I am not sure what's different in your case as that code fragment works for most people who have tried it.  Can you confirm that it actually didn't connect, rather than the UI just didn't show the changes?

**Comment by skorasaurus** [comment]
@Crell I was able to reproduce and confirm using an old environment. The error message that solr gives is `Uncaught PHP Exception Drupal\search_api_solr\SearchApiSolrException: "Solr HTTP error: HTTP request failed, Failed to connect to localhost port 8983: Connection refused" at /app/web/modules/contrib/search_api_solr/src/Plugin/search_api/backend/SearchApiSolrBackend.php line 809`

**Comment by skorasaurus** [comment]
also confirmed that echo $PLATFORM_RELATIONSHIPS | base64 --decode | json_pp returns solr.internal as the localhost. 

For what it's worth, and thivery well may be the culprit; we're still using an older versions of search_api_solr (1.0.0-alpha5) and search_api (1.0.0-alpha16),  as we have other custom modules that are reliant on older versions of this and other modules and are in the processing of updating them to the newer stable versions.

**Comment by Crell** [comment]
Ah ha!  Yes, earlier versions of Search API had a critical bug where it wouldn't recognize config overrides from settings.php at all.  That was fixed by some ugly deep work in both core and Search API (or maybe it was Search API Solr, I forget which).  If you're not running a fairly recent version of both then it's very likely that it is simply ignoring config overrides, no matter what you do.

I'd strongly suggest updating your custom modules for the current stable Search API versions.  Not only will that let you resolve this issue, but alpha modules get no security support.
